sensor:
  - platform: wifi_signal
    id: esphome_tesla_ble_wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    id: esphome_tesla_ble_uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

binary_sensor:
  - platform: status
    id: esphome_tesla_ble_status
    name: "Status"
  - platform: ble_presence
    id: esphome_tesla_ble_ble_status
    mac_address: $ble_mac_address
    device_class: connectivity
    name: "BLE Status"
    entity_category: diagnostic
    timeout: $ble_presence_timeout

text_sensor:
  - platform: version
    id: esphome_tesla_ble_version
    name: "Version"
    icon: mdi:cube-outline
  - platform: wifi_info
    ip_address:
      name: "IP Address"

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    id: esphome_tesla_ble_restart
    name: Restart
    icon: mdi:restart
    entity_category: diagnostic
